## 데이터 전처리

In [1]:
import pandas as pd

In [13]:
## 데이터 셋 호출
travel_df = pd.read_csv('./dataset/tn_travel_F.csv')
loc_df = pd.read_csv('./dataset/tn_visit_area_info_F.csv')

In [43]:
## 데이터 확인
travel_df.head()

,TRAVEL_ID,TRAVEL_NM,TRAVELER_ID,TRAVEL_PURPOSE,TRAVEL_START_YMD,TRAVEL_END_YMD,MVMN_NM,TRAVEL_PERSONA,TRAVEL_MISSION,TRAVEL_MISSION_CHECK
0,e_e000003,F03,e000003,5,2023-04-30,2023-05-01,NaN,"대구,경북 방문/경상권 외 거주/40세 이상/자녀동반/일반미션",5,5;6;22
1,e_e000340,E03,e000340,10;11;2;6;9,2023-05-27,2023-05-30,자가용,강원 방문/수도권/강원 거주/40세 이상/자녀동반/일반미션,10;11;2;6;9,8;9;24
2,e_e000515,F06,e000515,1;11;3;4;6,2023-06-03,2023-06-07,자가용,"부산,울산,경남 방문/경상권 외 거주/40세 이상/3인 이상 친구/일반미션",1;11;3;4;6,3;24;6
3,e_e000571,E01,e000571,22;23;24;26;4,2023-05-24,2023-05-27,대중교통 등,강원 방문/거주지 구분 없음/39세 이하/특별미션,22;23;24;26;4,23;22;26
4,e_e000601,F02,e000601,22;8;5;27;27;27;5;5;22;22;8;8,2023-05-26,2023-05-30,자가용,"대구,경북 방문/경상권 외 거주/39세 이하/나홀로 여행/일반미션",22;8;5;27;27;27;5;5;22;22;8;8,22;28;9

In [14]:
# 필요 데이터 추출
travel_df = travel_df[['TRAVEL_ID', 'TRAVEL_START_YMD', 'TRAVEL_END_YMD', 'TRAVEL_MISSION_CHECK']]
loc_df = loc_df[['TRAVEL_ID', 'POI_NM', 'X_COORD', 'Y_COORD', 'DGSTFN', 'SGG_CD']]

In [45]:
travel_df.head()

   TRAVEL_ID TRAVEL_START_YMD TRAVEL_END_YMD TRAVEL_MISSION_CHECK
0  e_e000003       2023-04-30     2023-05-01               5;6;22
1  e_e000340       2023-05-27     2023-05-30               8;9;24
2  e_e000515       2023-06-03     2023-06-07               3;24;6
3  e_e000571       2023-05-24     2023-05-27             23;22;26
4  e_e000601       2023-05-26     2023-05-30              22;28;9

In [46]:
loc_df.head()

   TRAVEL_ID  DGSTFN        SGG_CD
0  e_e000003     NaN           NaN
1  e_e000003     4.0           NaN
2  e_e000003     4.0  4.373031e+09
3  e_e000003     5.0           NaN
4  e_e000003     4.0           NaN

In [15]:
travelDF_f1 = pd.merge(loc_df,travel_df, on="TRAVEL_ID", how="left")
travelDF_f1.head()

,TRAVEL_ID,POI_NM,X_COORD,Y_COORD,DGSTFN,SGG_CD,TRAVEL_START_YMD,TRAVEL_END_YMD,TRAVEL_MISSION_CHECK
0,e_e000003,NaN,NaN,NaN,NaN,NaN,2023-04-30,2023-05-01,5;6;22
1,e_e000003,안성휴게소 부산방향,127.144690,37.013556,4.0,NaN,2023-04-30,2023-05-01,5;6;22
2,e_e000003,금강휴게소,127.672032,36.279001,4.0,4.373031e+09,2023-04-30,2023-05-01,5;6;22
3,e_e000003,김천종합운동장,128.086424,36.139677,5.0,NaN,2023-04-30,2023-05-01,5;6;22
4,e_e000003,입장거봉포도휴게소 서울방향,127.192712,36.943005,4.0,NaN,2023-04-30,2023-05-01,5;6;22

In [16]:
travelDF_f1.dropna(inplace=True) # 결측치 제거
print(travelDF_f1.isnull().sum()) # 결측치 확인

TRAVEL_ID               0
POI_NM                  0
X_COORD                 0
Y_COORD                 0
DGSTFN                  0
SGG_CD                  0
TRAVEL_START_YMD        0
TRAVEL_END_YMD          0
TRAVEL_MISSION_CHECK    0
dtype: int64

In [49]:
travelDF_f1.head()

,TRAVEL_ID,DGSTFN,SGG_CD,TRAVEL_START_YMD,TRAVEL_END_YMD,TRAVEL_MISSION_CHECK
2,e_e000003,4.0,4.373031e+09,2023-04-30,2023-05-01,5;6;22
12,e_e000340,5.0,4.165040e+09,2023-05-27,2023-05-30,8;9;24
19,e_e000340,5.0,4.165038e+09,2023-05-27,2023-05-30,8;9;24
74,e_e001062,5.0,4.127311e+09,2023-05-27,2023-05-30,7;21;22
76,e_e001062,5.0,4.127311e+09,2023-05-27,2023-05-30,7;21;22

In [17]:
travelDF_f1['TRAVEL_END_YMD'] = pd.to_datetime(travelDF_f1['TRAVEL_END_YMD'])
travelDF_f1['TRAVEL_START_YMD'] = pd.to_datetime(travelDF_f1['TRAVEL_START_YMD'])

travelDF_f1['date_diff'] = (travelDF_f1['TRAVEL_END_YMD'] - travelDF_f1['TRAVEL_START_YMD']).dt.days
travelDF_f1.drop(columns=['TRAVEL_START_YMD','TRAVEL_END_YMD'], inplace=True)
travelDF_f1.head()

,TRAVEL_ID,POI_NM,X_COORD,Y_COORD,DGSTFN,SGG_CD,TRAVEL_MISSION_CHECK,date_diff
2,e_e000003,금강휴게소,127.672032,36.279001,4.0,4.373031e+09,5;6;22,1
152,f_f000007,시소조개구이,129.102249,35.136467,5.0,2.629011e+09,4;21;3,3
200,f_f000014,프롬스톤,127.239628,37.923587,3.0,4.165034e+09,6;3;12,1
215,f_f000015,시례정가든,128.986136,35.582147,4.0,4.827034e+09,28;27;24,2
231,f_f000021,오색온천장,128.448256,38.078880,5.0,4.283031e+09,28;10;21,3

In [18]:
# 위치정보 필요부분만 남기기
travelDF_f1['SGG_CD'] = travelDF_f1['SGG_CD'].astype(str).str[:5].astype(float).astype(int)
travelDF_f1.head()

,TRAVEL_ID,POI_NM,X_COORD,Y_COORD,DGSTFN,SGG_CD,TRAVEL_MISSION_CHECK,date_diff
2,e_e000003,금강휴게소,127.672032,36.279001,4.0,43730,5;6;22,1
152,f_f000007,시소조개구이,129.102249,35.136467,5.0,26290,4;21;3,3
200,f_f000014,프롬스톤,127.239628,37.923587,3.0,41650,6;3;12,1
215,f_f000015,시례정가든,128.986136,35.582147,4.0,48270,28;27;24,2
231,f_f000021,오색온천장,128.448256,38.078880,5.0,42830,28;10;21,3

In [19]:
# 중복 데이터 제거
travelDF_f1 = travelDF_f1.drop_duplicates()
travelDF_f1.head()

,TRAVEL_ID,POI_NM,X_COORD,Y_COORD,DGSTFN,SGG_CD,TRAVEL_MISSION_CHECK,date_diff
2,e_e000003,금강휴게소,127.672032,36.279001,4.0,43730,5;6;22,1
152,f_f000007,시소조개구이,129.102249,35.136467,5.0,26290,4;21;3,3
200,f_f000014,프롬스톤,127.239628,37.923587,3.0,41650,6;3;12,1
215,f_f000015,시례정가든,128.986136,35.582147,4.0,48270,28;27;24,2
231,f_f000021,오색온천장,128.448256,38.078880,5.0,42830,28;10;21,3

In [20]:
# ID 값 제거
travelDF_f1.drop(columns=['TRAVEL_ID'], inplace=True)
travelDF_f1.head()

,POI_NM,X_COORD,Y_COORD,DGSTFN,SGG_CD,TRAVEL_MISSION_CHECK,date_diff
2,금강휴게소,127.672032,36.279001,4.0,43730,5;6;22,1
152,시소조개구이,129.102249,35.136467,5.0,26290,4;21;3,3
200,프롬스톤,127.239628,37.923587,3.0,41650,6;3;12,1
215,시례정가든,128.986136,35.582147,4.0,48270,28;27;24,2
231,오색온천장,128.448256,38.078880,5.0,42830,28;10;21,3

In [21]:
# 미션값 리스트로
travelDF_f1['TRAVEL_MISSION_CHECK'] = travelDF_f1['TRAVEL_MISSION_CHECK'].str.split(';')
travelDF_f1.head()

,POI_NM,X_COORD,Y_COORD,DGSTFN,SGG_CD,TRAVEL_MISSION_CHECK,date_diff
2,금강휴게소,127.672032,36.279001,4.0,43730,"[5, 6, 22]",1
152,시소조개구이,129.102249,35.136467,5.0,26290,"[4, 21, 3]",3
200,프롬스톤,127.239628,37.923587,3.0,41650,"[6, 3, 12]",1
215,시례정가든,128.986136,35.582147,4.0,48270,"[28, 27, 24]",2
231,오색온천장,128.448256,38.078880,5.0,42830,"[28, 10, 21]",3

In [22]:
travelDF_f1.columns = ['위치명','X 좌표','Y 좌표','만족도', '지역코드','여행 목적','여행 일수']
travelDF_f1 = travelDF_f1[['위치명','X 좌표','Y 좌표','지역코드','여행 목적','여행 일수','만족도']]
travelDF_f1.head()

        위치명        X 좌표       Y 좌표   지역코드         여행 목적  여행 일수  만족도
2     금강휴게소  127.672032  36.279001  43730    [5, 6, 22]      1  4.0
152  시소조개구이  129.102249  35.136467  26290    [4, 21, 3]      3  5.0
200    프롬스톤  127.239628  37.923587  41650    [6, 3, 12]      1  3.0
215   시례정가든  128.986136  35.582147  48270  [28, 27, 24]      2  4.0
231   오색온천장  128.448256  38.078880  42830  [28, 10, 21]      3  5.0

In [23]:
travelDF_f1.to_csv('dataset/train_travel_F.csv', index=False)

In [2]:
## 데이터 셋 호출
train_travel_E_df = pd.read_csv('./train_dataset/train_travel_E.csv')
train_travel_F_df = pd.read_csv('./train_dataset/train_travel_F.csv')
train_travel_G_df = pd.read_csv('./train_dataset/train_travel_G.csv')
train_travel_H_df = pd.read_csv('./train_dataset/train_travel_H.csv')
test_travel_E_df = pd.read_csv('./test_dataset/test_travel_E.csv')
test_travel_F_df = pd.read_csv('./test_dataset/test_travel_F.csv')
test_travel_G_df = pd.read_csv('./test_dataset/test_travel_G.csv')
test_travel_H_df = pd.read_csv('./test_dataset/test_travel_H.csv')

train_travel_A_df = pd.concat([train_travel_E_df,train_travel_F_df,train_travel_G_df,train_travel_H_df])
test_travel_A_df = pd.concat([test_travel_E_df,test_travel_F_df,test_travel_G_df,test_travel_H_df])

train_travel_A_df.to_csv('train_dataset/train_travel_A.csv', index=False)
test_travel_A_df.to_csv('test_dataset/tast_travel_A.csv', index=False)