## 데이터프레임 로드

In [28]:
import pandas as pd

travel = "dataset/travel.csv"
traveller = "dataset/traveller_master.csv"
loc = "dataset/visit_area_info.csv"

travelDF = pd.read_csv(travel, encoding="utf-8")
travellerDF = pd.read_csv(traveller, encoding="utf-8")
locDF = pd.read_csv(loc, encoding="utf-8")

travelDF.head()

,TRAVEL_ID,TRAVEL_NM,TRAVELER_ID,TRAVEL_PURPOSE,TRAVEL_START_YMD,TRAVEL_END_YMD,MVMN_NM,TRAVEL_PERSONA,TRAVEL_MISSION,TRAVEL_MISSION_CHECK
0,e_e000003,F03,e000003,5,2023-04-30,2023-05-01,NaN,"대구,경북 방문/경상권 외 거주/40세 이상/자녀동반/일반미션",5,5;6;22
1,e_e000340,E03,e000340,10;11;2;6;9,2023-05-27,2023-05-30,자가용,강원 방문/수도권/강원 거주/40세 이상/자녀동반/일반미션,10;11;2;6;9,8;9;24
2,e_e000515,F06,e000515,1;11;3;4;6,2023-06-03,2023-06-07,자가용,"부산,울산,경남 방문/경상권 외 거주/40세 이상/3인 이상 친구/일반미션",1;11;3;4;6,3;24;6
3,e_e000571,E01,e000571,22;23;24;26;4,2023-05-24,2023-05-27,대중교통 등,강원 방문/거주지 구분 없음/39세 이하/특별미션,22;23;24;26;4,23;22;26
4,e_e000601,F02,e000601,22;8;5;27;27;27;5;5;22;22;8;8,2023-05-26,2023-05-30,자가용,"대구,경북 방문/경상권 외 거주/39세 이하/나홀로 여행/일반미션",22;8;5;27;27;27;5;5;22;22;8;8,22;28;9

In [29]:
travelDF_f = travelDF[["TRAVEL_ID","TRAVELER_ID"]]
travelDF_f.head()

   TRAVEL_ID TRAVELER_ID
0  e_e000003     e000003
1  e_e000340     e000340
2  e_e000515     e000515
3  e_e000571     e000571
4  e_e000601     e000601

In [30]:
travellerDF.head()

,TRAVELER_ID,RESIDENCE_SGG_CD,GENDER,AGE_GRP,EDU_NM,EDU_FNSH_SE,MARR_STTS,FAMILY_MEMB,JOB_NM,JOB_ETC,...,TRAVEL_STYL_7,TRAVEL_STYL_8,TRAVEL_STATUS_RESIDENCE,TRAVEL_STATUS_DESTINATION,TRAVEL_STATUS_ACCOMPANY,TRAVEL_STATUS_YMD,TRAVEL_MOTIVE_1,TRAVEL_MOTIVE_2,TRAVEL_MOTIVE_3,TRAVEL_COMPANIONS_NUM
0,f000531,41,여,40,6,1,1,1,2,NaN,...,4,6,경기도,부산,나홀로 여행,2023-05-26~2023-05-28,2,1.0,4.0,0
1,f009186,27,남,60,4,1,2,2,4,NaN,...,4,6,대구광역시,경북,3대 동반 여행(친척 포함),2023-08-27~2023-08-27,6,3.0,1.0,3
2,f016521,48,여,30,6,1,2,3,2,NaN,...,2,7,경상남도,경북,3인 이상 여행(가족 외),2023-09-09~2023-09-09,8,3.0,1.0,2
3,f002539,48,남,50,5,1,2,3,3,NaN,...,5,3,경상남도,경남,부모 동반 여행,2023-06-03~2023-06-04,3,2.0,10.0,3
4,f005129,30,남,20,6,1,1,3,2,NaN,...,7,2,대전광역시,경북,2인 여행(가족 외),2023-07-31~2023-08-01,2,3.0,7.0,1

In [34]:
travellerDF_f = travellerDF[["TRAVELER_ID","GENDER","AGE_GRP"]]
travellerDF_f.head()

  TRAVELER_ID GENDER  AGE_GRP
0     f000531      여       40
1     f009186      남       60
2     f016521      여       30
3     f002539      남       50
4     f005129      남       20

In [35]:
locDF.head()

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,LOTNO_ADDR,X_COORD,Y_COORD,...,POI_NM,RESIDENCE_TIME_MIN,VISIT_AREA_TYPE_CD,REVISIT_YN,VISIT_CHC_REASON_CD,LODGING_TYPE_CD,DGSTFN,REVISIT_INTENTION,RCMDTN_INTENTION,SGG_CD
0,2304300001,e_e000003,1,집,2023-04-30,2023-04-30,경기 김포시 풍년로 19,경기 김포시 사우동 857,NaN,NaN,...,NaN,NaN,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2304300002,e_e000003,2,안성휴게소 부산방향,2023-04-30,2023-04-30,경기 안성시 원곡면 경부고속도로 365,경기 안성시 원곡면 반제리 642-6,127.144690,37.013556,...,안성휴게소 부산방향,30.0,9,Y,6.0,NaN,4.0,4.0,4.0,NaN
2,2304300003,e_e000003,3,금강휴게소,2023-04-30,2023-04-30,금강로 596,NaN,127.672032,36.279001,...,금강휴게소,30.0,9,N,6.0,NaN,4.0,4.0,4.0,4.373031e+09
3,2304300004,e_e000003,4,김천종합운동장,2023-04-30,2023-04-30,경북 김천시 운동장길 1,경북 김천시 삼락동 488-1,128.086424,36.139677,...,김천종합운동장,270.0,5,N,11.0,NaN,5.0,5.0,5.0,NaN
4,2304300005,e_e000003,5,입장 거봉포도 휴게소 서울 방향,2023-04-30,2023-04-30,충남 천안시 서북구 입장면 연곡길 407,충남 천안시 서북구 입장면 가산리 362-2,127.192712,36.943005,...,입장거봉포도휴게소 서울방향,30.0,9,N,9.0,NaN,4.0,4.0,4.0,NaN

In [36]:
locDF_f = locDF[["TRAVEL_ID","VISIT_AREA_NM","X_COORD","Y_COORD","DGSTFN"]]
locDF_f.head()

   TRAVEL_ID      VISIT_AREA_NM     X_COORD    Y_COORD  DGSTFN
0  e_e000003                  집         NaN        NaN     NaN
1  e_e000003         안성휴게소 부산방향  127.144690  37.013556     4.0
2  e_e000003              금강휴게소  127.672032  36.279001     4.0
3  e_e000003            김천종합운동장  128.086424  36.139677     5.0
4  e_e000003  입장 거봉포도 휴게소 서울 방향  127.192712  36.943005     4.0

In [37]:
travelDF_f1 = pd.merge(travelDF_f,travellerDF_f, on="TRAVELER_ID", how="left")
travelDF_f1.head()

   TRAVEL_ID TRAVELER_ID GENDER  AGE_GRP
0  e_e000003     e000003      남       40
1  e_e000340     e000340      여       40
2  e_e000515     e000515      남       40
3  e_e000571     e000571      여       30
4  e_e000601     e000601      여       20

In [38]:
travelDF_f2 = pd.merge(locDF_f, travelDF_f1, on="TRAVEL_ID", how="left")
travelDF_f2.head()

,TRAVEL_ID,VISIT_AREA_NM,X_COORD,Y_COORD,DGSTFN,TRAVELER_ID,GENDER,AGE_GRP
0,e_e000003,집,NaN,NaN,NaN,e000003,남,40
1,e_e000003,안성휴게소 부산방향,127.144690,37.013556,4.0,e000003,남,40
2,e_e000003,금강휴게소,127.672032,36.279001,4.0,e000003,남,40
3,e_e000003,김천종합운동장,128.086424,36.139677,5.0,e000003,남,40
4,e_e000003,입장 거봉포도 휴게소 서울 방향,127.192712,36.943005,4.0,e000003,남,40

In [40]:
#print(travelDF_f2.isnull().sum()) # 결측치 확인
"""
TRAVEL_ID           0
VISIT_AREA_NM       0
X_COORD          6927
Y_COORD          6927
DGSTFN           5540
TRAVELER_ID         0
GENDER              0
AGE_GRP             0
dtype: int64
"""
travelDF_f2.dropna(inplace=True) # 결측치 제거
print(travelDF_f2.isnull().sum()) # 결측치 확인

TRAVEL_ID        0
VISIT_AREA_NM    0
X_COORD          0
Y_COORD          0
DGSTFN           0
TRAVELER_ID      0
GENDER           0
AGE_GRP          0
dtype: int64

In [43]:
finalDF = travelDF_f2.drop(columns=["TRAVEL_ID","TRAVELER_ID"])
finalDF.head()

       VISIT_AREA_NM     X_COORD    Y_COORD  DGSTFN GENDER  AGE_GRP
1         안성휴게소 부산방향  127.144690  37.013556     4.0      남       40
2              금강휴게소  127.672032  36.279001     4.0      남       40
3            김천종합운동장  128.086424  36.139677     5.0      남       40
4  입장 거봉포도 휴게소 서울 방향  127.192712  36.943005     4.0      남       40
7               자유 궁  127.247150  37.964150     4.0      여       40

In [51]:
print(int(finalDF[["DGSTFN"]].values[1]))

4

C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\2440992698.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(int(finalDF[["DGSTFN"]].values[1]))

In [52]:
for idx,dgs in enumerate(finalDF[["DGSTFN"]].values):
    dgs_int = int(dgs)
    if dgs_int==1:
        finalDF.at[idx, 'DGSTFN'] = "매우 불만족"
    elif dgs_int==2:
        finalDF.at[idx, 'DGSTFN']="불만족"
    elif dgs_int==3:
        finalDF.at[idx, 'DGSTFN']="보통"
    elif dgs_int==4:
        finalDF.at[idx, 'DGSTFN']="만족"
    elif dgs_int==5:
        finalDF.at[idx, 'DGSTFN']="매우 만족"

finalDF.head()

C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '만족' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  finalDF.at[idx, 'DGSTFN']="만족"
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)
C:\Users\human-20\AppData\Local\Temp\ipykernel_16220\126746475.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dgs_int = int(dgs)

       VISIT_AREA_NM     X_COORD    Y_COORD DGSTFN GENDER  AGE_GRP
1         안성휴게소 부산방향  127.144690  37.013556     만족      남     40.0
2              금강휴게소  127.672032  36.279001  매우 만족      남     40.0
3            김천종합운동장  128.086424  36.139677     만족      남     40.0
4  입장 거봉포도 휴게소 서울 방향  127.192712  36.943005     만족      남     40.0
7               자유 궁  127.247150  37.964150     보통      여     40.0

In [53]:
finalDF.columns=["방문지 이름","X 좌표","Y 좌표","만족도","방문자 성별","방문자 나이대"]
finalDF.head()

              방문지 이름        X 좌표       Y 좌표    만족도 방문자 성별  방문자 나이대
1         안성휴게소 부산방향  127.144690  37.013556     만족      남     40.0
2              금강휴게소  127.672032  36.279001  매우 만족      남     40.0
3            김천종합운동장  128.086424  36.139677     만족      남     40.0
4  입장 거봉포도 휴게소 서울 방향  127.192712  36.943005     만족      남     40.0
7               자유 궁  127.247150  37.964150     보통      여     40.0

In [ ]:
# 인기 지역 탐색
finalDF

## LLM 에게 해당 데이터셋 학습

In [ ]:
from langchain.chains import RetrievalQA
from langchain.document_loaders import TextLoader
from langchain.vectorstores import FAISS
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.llms import Ollama

# 임베딩 모델
embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# llm 모델
llm_model = Ollama(model="gemma3:4b", base_url="http://localhost:11434")